hopefully fixed build scrip

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -426,7 +426,7 @@ jobs:
         uses: actions/upload-artifact@v4.6.2
         with:
           name: ${{ needs.info.outputs.project_file_name }}-curseforge
-          path: ./build/curseforge/*-curseforge.zip
+          path: ./build/curseforge/${{ needs.info.outputs.project_file_name }}-curseforge.zip
           if-no-files-found: error
 
       # - name: Preparing the modrinth artifact 
@@ -466,16 +466,13 @@ jobs:
       - name: Preparing the server artifact
         run: |
           cd ./build/serverpack/
-          FILE=$(find . -maxdepth 1 -name "*.zip" -printf "%f\n" | head -n1)
-          NEW_FILE="${FILE%.zip}-serverpack.zip"
-          mv "$FILE" "$NEW_FILE"
-          echo "file=$NEW_FILE" >> "$GITHUB_OUTPUT"
+          mv *.zip "$(basename -s .zip *.zip)-serverpack.zip"
 
       - name: Upload server artifact
         uses: actions/upload-artifact@v4.6.2
         with:
           name: ${{ needs.info.outputs.project_file_name }}-serverpack
-          path: ./build/serverpack/${{ steps.serverpack.outputs.file }}
+          path: ./build/serverpack/${{ needs.info.outputs.project_file_name }}-serverpack.zip
           if-no-files-found: error
 
   release-github:
@@ -483,8 +480,6 @@ jobs:
     needs: [info, build-project]
     runs-on: ubuntu-latest
     if: ${{ needs.info.outputs.make_release == 'true' }}
-    permissions:
-      contents: write
     outputs:
       url: ${{ steps.release.outputs.url }}
 
@@ -540,55 +535,55 @@ jobs:
           generate_release_notes: true
           token: ${{ secrets.GITHUB_TOKEN }}
 
-  # release-curseforge:
-  #   name: Release to CurseForge
-  #   needs: [info, build-project, release-github]
-  #   runs-on: ubuntu-latest
-  #   if: ${{ needs.info.outputs.make_release == 'true' }}
-  #   outputs:
-  #     id: ${{ steps.release.outputs.id }}
-  # 
-  #   steps:
-  #     - name: Check if CURSEFORGE_TOKEN exists
-  #       shell: bash
-  #       run: |
-  #         if [ "${{ secrets.CURSEFORGE_TOKEN }}" == '' ]; then
-  #           echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-  #         fi  
-  # 
-  #     - name: Download artifact
-  #       uses: actions/download-artifact@v5.0.0
-  #       with:
-  #         merge-multiple: true
-  # 
-  #     - name: Check if artifact exists
-  #       id: check_artifact
-  #       shell: bash
-  #       run: |
-  #         if [ ! -f ${{ needs.info.outputs.project_file_name }}-curseforge.zip ]; then
-  #           echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
-  #         fi
-  #         if [ ! -f ${{ needs.info.outputs.project_file_name }}-serverpack.zip ]; then
-  #           echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
-  #         fi
-  #         echo "All artifacts found"
-  # 
-  #     - name: Upload to Curseforge
-  #       id: release
-  #       uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-  #       with:
-  #         api-token: ${{ secrets.CURSEFORGE_TOKEN }}
-  #         project-id: ${{ vars.CURSEFORGE_ID }}
-  #         display-name: ${{ needs.info.outputs.project_full_name }}
-  #         modpack-path: ${{ needs.info.outputs.project_file_name }}-curseforge.zip
-  #         server-display-name: ${{ needs.info.outputs.project_full_name }} Serverpack
-  #         modpack-server-path: ${{ needs.info.outputs.project_file_name }}-serverpack.zip
-  #         changelog: |
-  #           ${{ needs.info.outputs.changelog }}
-  #           ${{ needs.info.outputs.diff }}
-  #         changelog-format: markdown
-  #         game-version: ${{ needs.info.outputs.mc_version }}
-  #         release-type: ${{ needs.info.outputs.release_type }}
+  #release-curseforge:
+  #  name: Release to CurseForge
+  #  needs: [info, build-project, release-github]
+  #  runs-on: ubuntu-latest
+  #  if: ${{ needs.info.outputs.make_release == 'true' }}
+  #  outputs:
+  #    id: ${{ steps.release.outputs.id }}
+#
+  #  steps:
+  #    - name: Check if CURSEFORGE_TOKEN exists
+  #      shell: bash
+  #      run: |
+  #        if [ "${{ secrets.CURSEFORGE_TOKEN }}" == '' ]; then
+  #          echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+  #        fi  
+#
+  #    - name: Download artifact
+  #      uses: actions/download-artifact@v5.0.0
+  #      with:
+  #        merge-multiple: true
+#
+  #    - name: Check if artifact exists
+  #      id: check_artifact
+  #      shell: bash
+  #      run: |
+  #        if [ ! -f ${{ needs.info.outputs.project_file_name }}-curseforge.zip ]; then
+  #          echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
+  #        fi
+  #        if [ ! -f ${{ needs.info.outputs.project_file_name }}-serverpack.zip ]; then
+  #          echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
+  #        fi
+  #        echo "All artifacts found"
+#
+  #    - name: Upload to Curseforge
+  #      id: release
+  #      uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+  #      with:
+  #        api-token: ${{ secrets.CURSEFORGE_TOKEN }}
+  #        project-id: ${{ vars.CURSEFORGE_ID }}
+  #        display-name: ${{ needs.info.outputs.project_full_name }}
+  #        modpack-path: ${{ needs.info.outputs.project_file_name }}-curseforge.zip
+  #        server-display-name: ${{ needs.info.outputs.project_full_name }} Serverpack
+  #        modpack-server-path: ${{ needs.info.outputs.project_file_name }}-serverpack.zip
+  #        changelog: |
+  #          ${{ needs.info.outputs.changelog }}
+  #          ${{ needs.info.outputs.diff }}
+  #        changelog-format: markdown
+  #        game-version: ${{ needs.info.outputs.mc_version }}
+  #        release-type: ${{ needs.info.outputs.release_type }}
 
   # release-modrinth:
   #     name: Release to Modrinth
@@ -636,7 +631,7 @@ jobs:
 
   discord-message:
     name: Discord Message
-    needs: [info, release-github]
+    needs: [info, release-github, release-curseforge]
     runs-on: ubuntu-latest
     if: needs.info.outputs.webhook_present == 'true'
     steps:
@@ -651,7 +646,7 @@ jobs:
         uses: hugoalh/send-discord-webhook-ghaction@v7.0.5
         with:
           key: ${{ secrets.discord_webhook  }}
-          username: "releases" # Change this!
+          username: "ModPack" # Change this!
           avatar_url: "https://media.forgecdn.net/avatars/thumbnails/798/822/64/64/638160732420962168.png" # Change this! (and the below curseforge url)
           content_links_no_embed: .+
           content: |
@@ -659,7 +654,7 @@ jobs:
             **Release Type**: `${{ needs.info.outputs.release_type }}`
             **Game Version**: `${{ needs.info.outputs.mc_version }}`
           
-            [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)
+            [CurseForge](https://www.curseforge.com/minecraft/modpacks/template-pack/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)
             ```markdown
             ${{ steps.truncated.outputs.text  }}
             - ...```
